# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-09 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0002_auto_20161208_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
