# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-10 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0007_remove_sales_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admindashboard.Customers'),
            preserve_default=False,
        ),
    ]
