# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-10 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0008_sales_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='actual_amount',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='balance_amount',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='payment_history',
            name='actual_amount',
            field=models.FloatField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='payment_history',
            name='balance_amount',
            field=models.FloatField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='payment_history',
            name='discount_amount',
            field=models.FloatField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='payment_history',
            name='tax_amount',
            field=models.FloatField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='payment_history',
            name='total_amount',
            field=models.FloatField(blank=True, max_length=225, null=True),
        ),
    ]
