# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-10 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0009_auto_20161210_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='actual_amount',
        ),
        migrations.RemoveField(
            model_name='service',
            name='balance_amount',
        ),
        migrations.RemoveField(
            model_name='service',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='service',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_amount',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tax_amount',
        ),
        migrations.AddField(
            model_name='service',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admindashboard.Product'),
            preserve_default=False,
        ),
    ]
