# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0010_auto_20161210_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.CharField(blank=True, max_length=520, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('otherdetails', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='service_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
