# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0012_enquiry_enquiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Open'), (0, 'Closed')], null=True),
        ),
    ]
