# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-17 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0014_auto_20161215_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_history',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admindashboard.Service'),
            preserve_default=False,
        ),
    ]
